feat(models): Add database model and migrations
4GeeksAcademy/kusi pull request #1
Opened 2024-09-11 22:41 UTC by ManuelLoaizaV

Tables:
- [ ] User
- [ ] Role
- [ ] Dish
- [ ] Ingredient
- [ ] DishIngredient
- [ ] Order
- [ ] OrderDish

Chores:
- [ ] Create diagram in drawio.
- [ ] Make migrations.

2024-09-12 20:03 UTC, AngelCrispin approved these changes
Ta gud

2024-09-12 20:24 UTC, AngelCrispin requested changes

2024-09-12 20:24 UTC, AngelCrispin commented on src/api/models.py
> +    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)
Falta quantity

2024-09-12 20:37 UTC, ManuelLoaizaV commented on src/api/models.py
> +    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)
Nice catch, thanks!

2024-09-13 17:37 UTC, ROZZYNUEZ14 commented
👍

2024-09-13 17:38 UTC, ROZZYNUEZ14 approved these changes

2024-09-13 21:51 UTC, AngelCrispin approved these changes
LGFA

2024-09-13 21:51 UTC, merged